// ─────────────────────────────────────────────────────────────────────────────
// Topic Report Generator — creates comprehensive Markdown reports from
// evidence data. Pulls together all sources, tiers, and insights for a topic.
// ─────────────────────────────────────────────────────────────────────────────

import type { EvidencePiece, EvidenceTier } from "@/lib/evidence";
import { tierMeta } from "@/lib/evidence";
import type { NormalizedEvidence } from "@/lib/ingestion/types";
import { classifyTierAdvanced } from "@/lib/evidence-classifier";
import { parseAbstract } from "@/lib/abstract-parser-v2";

export interface ReportOptions {
  /** Include evidence quality breakdown */
  includeQualityBreakdown?: boolean;
  /** Include source distribution */
  includeSourceDistribution?: boolean;
  /** Include timeline */
  includeTimeline?: boolean;
  /** Include key findings */
  includeKeyFindings?: boolean;
  /** Include recommendations section */
  includeRecommendations?: boolean;
  /** Max items per section */
  maxItems?: number;
}

const DEFAULT_OPTIONS: ReportOptions = {
  includeQualityBreakdown: true,
  includeSourceDistribution: true,
  includeTimeline: true,
  includeKeyFindings: true,
  includeRecommendations: true,
  maxItems: 20,
};

/**
 * Generate a comprehensive Markdown report for a topic.
 */
export function generateTopicReport(
  topicId: string,
  topicName: string,
  evidence: EvidencePiece[],
  opts: ReportOptions = {},
): string {
  const options = { ...DEFAULT_OPTIONS, ...opts };
  const now = new Date();
  const lines: string[] = [];

  // ── Header ──
  lines.push(`# ${topicName} — Evidence Report`);
  lines.push("");
  lines.push(
    `> Generated by PRAN on ${now.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
  );
  lines.push(`> Total evidence pieces: ${evidence.length}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // ── Executive Summary ──
  lines.push("## Executive Summary");
  lines.push("");
  lines.push(generateExecutiveSummary(evidence));
  lines.push("");

  // ── Evidence Quality Breakdown ──
  if (options.includeQualityBreakdown) {
    lines.push("## Evidence Quality Distribution");
    lines.push("");
    lines.push(generateQualityBreakdown(evidence));
    lines.push("");
  }

  // ── Source Distribution ──
  if (options.includeSourceDistribution) {
    lines.push("## Source Distribution");
    lines.push("");
    lines.push(generateSourceDistribution(evidence));
    lines.push("");
  }

  // ── Key Findings ──
  if (options.includeKeyFindings) {
    lines.push("## Key Findings");
    lines.push("");
    lines.push(generateKeyFindings(evidence, options.maxItems!));
    lines.push("");
  }

  // ── Timeline ──
  if (options.includeTimeline) {
    lines.push("## Publication Timeline");
    lines.push("");
    lines.push(generateTimeline(evidence));
    lines.push("");
  }

  // ── Recommendations ──
  if (options.includeRecommendations) {
    lines.push("## Recommendations");
    lines.push("");
    lines.push(generateRecommendations(evidence));
    lines.push("");
  }

  // ── Evidence Table ──
  lines.push("## Evidence Table");
  lines.push("");
  lines.push(generateEvidenceTable(evidence, options.maxItems!));
  lines.push("");

  // ── Footer ──
  lines.push("---");
  lines.push("");
  lines.push("*This report was generated by PRAN (Platform for Research Analysis of N-evidence).*");
  lines.push("*Evidence tiers are classified using methodology-aware pattern analysis.*");
  lines.push("*Confidence scores reflect tier quality, recency, and sample size.*");

  return lines.join("\n");
}

/**
 * Generate a report from NormalizedEvidence (from ingestion layer).
 */
export function generateReportFromNormalized(
  topicId: string,
  topicName: string,
  items: NormalizedEvidence[],
  opts: ReportOptions = {},
): string {
  const evidence: EvidencePiece[] = items.map((item) => {
    const parsed = parseAbstract(item.abstract);
    const tier = classifyTierAdvanced(item.abstract || item.title, {
      source: item.sourceName,
    }).tier;

    return {
      id: item.id,
      title: item.title,
      tier,
      year: item.year,
      source: item.sourceName,
      authors: item.authors,
      journal: item.journal,
      n: parsed.sampleSize ?? item.sampleSize,
      effect: parsed.effectSize ?? item.effect,
      confidence: 0,
      url: item.url,
      abstract: item.abstract,
    };
  });

  return generateTopicReport(topicId, topicName, evidence, opts);
}

// ─────────────────────────────────────────────────────────────────────────────
// Section generators
// ─────────────────────────────────────────────────────────────────────────────

function generateExecutiveSummary(evidence: EvidencePiece[]): string {
  if (evidence.length === 0) {
    return "No evidence found for this topic. Consider broadening the search query.";
  }

  const byTier = groupByTier(evidence);
  const bySource = groupBySource(evidence);
  const years = evidence.map((e) => e.year).filter((y): y is number => y !== null);
  const avgConfidence = Math.round(
    evidence.reduce((sum, e) => sum + e.confidence, 0) / evidence.length,
  );

  const highTierCount = (byTier["meta-analysis"]?.length ?? 0) + (byTier["rct"]?.length ?? 0);
  const guidelineCount = byTier["guideline"]?.length ?? 0;

  const parts: string[] = [];

  parts.push(
    `This report synthesizes **${evidence.length} pieces of evidence** from **${Object.keys(bySource).length} sources**.`,
  );

  if (highTierCount > 0) {
    parts.push(
      `**${highTierCount} high-quality studies** (meta-analyses and RCTs) were identified.`,
    );
  }

  if (guidelineCount > 0) {
    parts.push(`**${guidelineCount} clinical guidelines** were found from major organizations.`);
  }

  if (years.length > 0) {
    const minYear = Math.min(...years);
    const maxYear = Math.max(...years);
    parts.push(`Evidence spans from **${minYear}** to **${maxYear}**.`);
  }

  parts.push(`Average confidence score: **${avgConfidence}%**.`);

  return parts.join(" ");
}

function generateQualityBreakdown(evidence: EvidencePiece[]): string {
  const byTier = groupByTier(evidence);
  const total = evidence.length;
  const lines: string[] = [];

  lines.push("| Tier | Count | Percentage | Avg Confidence |");
  lines.push("|------|-------|------------|----------------|");

  const tierOrder: EvidenceTier[] = [
    "meta-analysis",
    "rct",
    "guideline",
    "cohort",
    "case-report",
    "expert-opinion",
  ];

  for (const tier of tierOrder) {
    const items = byTier[tier] ?? [];
    if (items.length === 0) continue;

    const pct = Math.round((items.length / total) * 100);
    const avgConf = Math.round(items.reduce((sum, e) => sum + e.confidence, 0) / items.length);

    lines.push(`| ${tierMeta[tier].label} | ${items.length} | ${pct}% | ${avgConf}% |`);
  }

  return lines.join("\n");
}

function generateSourceDistribution(evidence: EvidencePiece[]): string {
  const bySource = groupBySource(evidence);
  const lines: string[] = [];

  lines.push("| Source | Count | Percentage |");
  lines.push("|--------|-------|------------|");

  const sorted = Object.entries(bySource).sort((a, b) => b[1].length - a[1].length);
  const total = evidence.length;

  for (const [source, items] of sorted) {
    const pct = Math.round((items.length / total) * 100);
    lines.push(`| ${source} | ${items.length} | ${pct}% |`);
  }

  return lines.join("\n");
}

function generateKeyFindings(evidence: EvidencePiece[], maxItems: number): string {
  // Sort by confidence, take top N
  const sorted = [...evidence].sort((a, b) => b.confidence - a.confidence).slice(0, maxItems);

  const lines: string[] = [];

  for (const item of sorted) {
    const tierLabel = tierMeta[item.tier]?.label ?? item.tier;
    const effect = item.effect ? ` — ${item.effect}` : "";
    lines.push(`- **[${tierLabel}]** ${item.title}${effect} (${item.year ?? "n.d."})`);
  }

  return lines.join("\n");
}

function generateTimeline(evidence: EvidencePiece[]): string {
  const byYear = new Map<number, EvidencePiece[]>();

  for (const item of evidence) {
    if (item.year === null) continue;
    const existing = byYear.get(item.year) ?? [];
    existing.push(item);
    byYear.set(item.year, existing);
  }

  if (byYear.size === 0) {
    return "No publication years available for timeline analysis.";
  }

  const sorted = [...byYear.entries()].sort((a, b) => a[0] - b[0]);
  const maxCount = Math.max(...sorted.map(([, items]) => items.length));

  const lines: string[] = [];
  lines.push("```");

  for (const [year, items] of sorted) {
    const barLength = Math.round((items.length / maxCount) * 30);
    const bar = "█".repeat(barLength);
    lines.push(`${year} │ ${bar} (${items.length})`);
  }

  lines.push("```");
  return lines.join("\n");
}

function generateRecommendations(evidence: EvidencePiece[]): string {
  const byTier = groupByTier(evidence);
  const lines: string[] = [];

  const metaCount = byTier["meta-analysis"]?.length ?? 0;
  const rctCount = byTier["rct"]?.length ?? 0;
  const guidelineCount = byTier["guideline"]?.length ?? 0;
  const cohortCount = byTier["cohort"]?.length ?? 0;

  if (metaCount >= 3) {
    lines.push(
      "- **Strong evidence base**: Multiple meta-analyses available. Consider conducting an updated systematic review.",
    );
  } else if (rctCount >= 3) {
    lines.push(
      "- **Moderate evidence base**: Several RCTs available but no meta-analysis. A systematic review would strengthen the evidence.",
    );
  } else if (rctCount + metaCount === 0 && cohortCount > 0) {
    lines.push(
      "- **Limited experimental evidence**: Only observational studies found. Randomized trials are needed to establish causality.",
    );
  } else if (evidence.length === 0) {
    lines.push(
      "- **No evidence found**: Consider broadening the search query or checking alternative data sources.",
    );
  }

  if (guidelineCount > 0) {
    lines.push(
      `- **Clinical guidelines available**: ${guidelineCount} guideline(s) from major organizations should be consulted for clinical decision-making.`,
    );
  }

  const recentEvidence = evidence.filter((e) => e.year && e.year >= new Date().getFullYear() - 3);
  if (recentEvidence.length > 0) {
    lines.push(
      `- **Recent evidence**: ${recentEvidence.length} studies published in the last 3 years.`,
    );
  } else if (evidence.length > 0) {
    lines.push(
      "- **Evidence recency**: Most evidence is older than 3 years. Newer studies may be needed.",
    );
  }

  if (lines.length === 0) {
    lines.push("- Insufficient evidence to provide specific recommendations at this time.");
  }

  return lines.join("\n");
}

function generateEvidenceTable(evidence: EvidencePiece[], maxItems: number): string {
  const sorted = [...evidence].sort((a, b) => b.confidence - a.confidence).slice(0, maxItems);

  const lines: string[] = [];
  lines.push("| # | Tier | Title | Year | Source | N | Confidence |");
  lines.push("|---|------|-------|------|--------|---|------------|");

  for (let i = 0; i < sorted.length; i++) {
    const item = sorted[i];
    const tierLabel = tierMeta[item.tier]?.label ?? item.tier;
    const title = item.title.length > 60 ? item.title.slice(0, 57) + "..." : item.title;
    const n = item.n ? item.n.toLocaleString() : "—";
    lines.push(
      `| ${i + 1} | ${tierLabel} | ${title} | ${item.year ?? "n.d."} | ${item.source} | ${n} | ${item.confidence}% |`,
    );
  }

  if (evidence.length > maxItems) {
    lines.push(
      `\n*Showing top ${maxItems} of ${evidence.length} evidence pieces (sorted by confidence).*`,
    );
  }

  return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function groupByTier(evidence: EvidencePiece[]): Record<string, EvidencePiece[]> {
  const groups: Record<string, EvidencePiece[]> = {};
  for (const item of evidence) {
    const key = item.tier;
    if (!groups[key]) groups[key] = [];
    groups[key].push(item);
  }
  return groups;
}

function groupBySource(evidence: EvidencePiece[]): Record<string, EvidencePiece[]> {
  const groups: Record<string, EvidencePiece[]> = {};
  for (const item of evidence) {
    const key = item.source;
    if (!groups[key]) groups[key] = [];
    groups[key].push(item);
  }
  return groups;
}
