/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as PyramidRouteImport } from './routes/pyramid'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as CourtroomRouteImport } from './routes/courtroom'
import { Route as ConflictsRouteImport } from './routes/conflicts'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PyramidRoute = PyramidRouteImport.update({
  id: '/pyramid',
  path: '/pyramid',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtroomRoute = CourtroomRouteImport.update({
  id: '/courtroom',
  path: '/courtroom',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsRoute = ConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/conflicts': typeof ConflictsRoute
  '/courtroom': typeof CourtroomRoute
  '/graph': typeof GraphRoute
  '/guidelines': typeof GuidelinesRoute
  '/pyramid': typeof PyramidRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/conflicts': typeof ConflictsRoute
  '/courtroom': typeof CourtroomRoute
  '/graph': typeof GraphRoute
  '/guidelines': typeof GuidelinesRoute
  '/pyramid': typeof PyramidRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/conflicts': typeof ConflictsRoute
  '/courtroom': typeof CourtroomRoute
  '/graph': typeof GraphRoute
  '/guidelines': typeof GuidelinesRoute
  '/pyramid': typeof PyramidRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canvas'
    | '/conflicts'
    | '/courtroom'
    | '/graph'
    | '/guidelines'
    | '/pyramid'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canvas'
    | '/conflicts'
    | '/courtroom'
    | '/graph'
    | '/guidelines'
    | '/pyramid'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/canvas'
    | '/conflicts'
    | '/courtroom'
    | '/graph'
    | '/guidelines'
    | '/pyramid'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasRoute: typeof CanvasRoute
  ConflictsRoute: typeof ConflictsRoute
  CourtroomRoute: typeof CourtroomRoute
  GraphRoute: typeof GraphRoute
  GuidelinesRoute: typeof GuidelinesRoute
  PyramidRoute: typeof PyramidRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyramid': {
      id: '/pyramid'
      path: '/pyramid'
      fullPath: '/pyramid'
      preLoaderRoute: typeof PyramidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courtroom': {
      id: '/courtroom'
      path: '/courtroom'
      fullPath: '/courtroom'
      preLoaderRoute: typeof CourtroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicts': {
      id: '/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof ConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasRoute: CanvasRoute,
  ConflictsRoute: ConflictsRoute,
  CourtroomRoute: CourtroomRoute,
  GraphRoute: GraphRoute,
  GuidelinesRoute: GuidelinesRoute,
  PyramidRoute: PyramidRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
